# Generated by Django 5.1.7 on 2025-04-25 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='strava_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stravaactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='stravaactivity',
            unique_together={('user', 'strava_id')},
        ),
    ]
