# Generated by Django 5.1.7 on 2025-04-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0002_stravaactivity_strava_id_stravaactivity_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='calories',
            field=models.IntegerField(null=True),
        ),
    ]
