# Generated by Django 5.1.5 on 2025-04-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='workout_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('yoga', 'Yoga')], default='strength', max_length=20),
            preserve_default=False,
        ),
    ]
