# Generated by Django 5.2 on 2025-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('strength', 'Strength'), ('cardio', 'Cardio'), ('nutrition', 'Nutrition')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
