# Generated by Django 5.2 on 2025-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_coach', '0002_coachingsession_category_coachingsession_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingsession',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='coachingsession',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('strength', 'Strength'), ('cardio', 'Cardio'), ('nutrition', 'Nutrition'), ('flexibility', 'Flexibility')], default='general', max_length=20),
        ),
    ]
