# Generated by Django 5.2 on 2025-04-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_coach', '0003_remove_coachingsession_is_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='is_helpful',
            field=models.BooleanField(null=True),
        ),
    ]
