# Generated by Django 5.2 on 2025-04-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_goal_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
