# Generated by Django 5.2 on 2025-04-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_goal_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="abandoned",
            field=models.BooleanField(default=False),
        ),
    ]
