# Generated by Django 5.2 on 2025-04-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
