# Generated by Django 5.2 on 2025-04-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='calories_burnt_per_second',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='goal',
            name='total_duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
