# Generated by Django 5.2 on 2025-04-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_goal_calories_burnt_per_second_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="progress",
            field=models.FloatField(default=0.0),
        ),
    ]
