# Generated by Django 5.2 on 2025-04-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_goal_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="total_calories_burnt",
            field=models.FloatField(default=0.0),
        ),
    ]
