# Generated by Django 5.2 on 2025-04-25 03:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_profile_total_calories_burnt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progress",
            name="target_value",
        ),
    ]
